### PR TITLE
Adds request timing flag, enabling logs for request's elapsed time

### LINKED ISSUE #53: Add response time into logs
Large prompts or extensive documents (knowledge base) can significantly lengthen the LLM's response time for certain tasks, and it would be helpful to observe this response time in the terminal while running uvicorn. It will be common for a developer to try different prompts to check the rensponse time.

### PR DESCRIPTION
**Pull request by vmesel**
Closes #53

### CODE REVIEW

**Comment by avelino** [comment]
@vmesel wouldn't adding the timestamp to the log solve the problem?
we're not counting the processing time automatically (I don't think we should, it's unnecessary complexity)

```log
2023-11-24 09:03:22,728 [uvicorn.error] INFO:     Started server process [21824]
2023-11-24 09:03:22,729 [uvicorn.error] INFO:     Waiting for application startup.
2023-11-24 09:03:22,729 [uvicorn.error] INFO:     Application startup complete.
2023-11-24 09:03:22,729 [uvicorn.error] INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2023-11-24 09:03:26,359 [uvicorn.access] INFO:     127.0.0.1:51932 - "POST /session HTTP/1.1" 200 OK
```

if you want to know the "response" time, take a look at the log and count it up:
`2023-11-24 09:03:22,729` - `2023-11-24 09:03:26,359`

**Comment by vmesel** [comment]
>if you want to know the "response" time, take a look at the log and count it up:
> 2023-11-24 09:03:22,729 - 2023-11-24 09:03:26,359

@avelino What happens if the server is up for 24h and we receive a request on the 25th h? Will it be a 25h-long request?

**Comment by avelino** [comment]
> What happens if the server is up for 24h and we receive a request on the 25th h? Will it be a 25h-long request?

@vmesel Is it a "real" problem or speculation? No speculation!

where will this resource be used, dev or production?
If we want to measure the response time of a prompt, this information needs to be in the log (stdout), so it's easy to count, which is why I proposed putting timestamp

I don't think it's a real response time of 25h, that would timeout the http server.

**Comment by matheusfrancisco** [comment]
i will leave my comments if you guys want measure request time on fastapi, it is a simple way.

```python
import time

from fastapi import FastAPI, Request

app = FastAPI()

@app.middleware("http")
async def add_process_time_header(request: Request, call_next):
    start_time = time.time()
    response = await call_next(request)
    process_time = time.time() - start_time
    response.headers["X-Process-Time"] = str(process_time)
    return response
```

**Comment by lgabs** [comment]
maybe this idea would be more simple for now?
https://github.com/talkdai/dialog/pull/62

**Comment by avelino** [comment]
I like the solution proposed by @lgabs in pr #62

cc @vmesel

**Comment by vmesel** [comment]
Closing this in favor of #62

**Pull request closed without merging**
