### PR TITLE
WIP: Better session management using dependency injection

### PR DESCRIPTION
**Pull request by walison17**
fixed: #149

### CODE REVIEW

**Comment by vmesel** [comment]
Is this the same as the #150?

**Comment by avelino** [comment]
> Is this the same as the #150?

@vmesel, my implementation is wrong, @walison17's is much better. I just closed the PR I opened.

**Comment by avelino** [comment]
@walison17 were you able to finish this PR?

**Comment by vmesel** [comment]
@walison17 My #171 PR conflicts with this one, can we merge all of these changes into one branch only?

**Comment by vmesel** [comment]
I'm closing this in order to maintain the change made in #173

**Pull request closed without merging**
